name: media_vault
description: "Media Vault Windows."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  file_picker: ^8.1.7
  provider: ^6.1.2
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  sqflite_common_ffi: ^2.3.4+4
  popover: ^0.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.8
  
flutter:
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: Media Vault
  certificate_path: D:\Media Vault\certificate\media_vault.pfx
  certificate_password: NhB9OY
  app_installer:
    publish_folder_path: D:\Media Vault
  msix_version: 1.0.0.0
  logo_path: C:\dev\media_vault\assets\logo.png
  capabilities: picturesLibrary, videosLibrary, musicLibrary, documentsLibrary, broadFileSystemAccess
  include: 
    - windows/runner/resources/sqlite3.dll